# Generated by Django 3.2.9 on 2021-11-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='text',
            new_name='טקסט',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='name',
            new_name='שם',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='תאריך',
        ),
    ]
