# Generated by Django 3.2.9 on 2021-11-29 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_auto_20211129_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='תאריך',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='שם',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='טקסט',
            new_name='text',
        ),
    ]
