# Generated by Django 3.2.9 on 2022-01-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success_story', '0002_alter_story_date_alter_story_name_alter_story_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='תיאור'),
        ),
    ]
