# Generated by Django 4.0 on 2022-01-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('success_story', '0002_alter_story_date_alter_story_name_alter_story_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
    ]
