# Generated by Django 3.2.9 on 2021-12-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='genre',
            field=models.CharField(choices=[('adoption', 'אימוץ'), ('info', 'מידע'), ('training', 'אילוף'), ('other', 'אחר')], default='other', max_length=200, verbose_name="ז'אנר"),
        ),
        migrations.AddField(
            model_name='articles',
            name='link',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='type',
            field=models.CharField(choices=[('cat', 'חתול'), ('dog', 'כלב')], max_length=10, verbose_name='סוג'),
        ),
    ]
