# Generated by Django 4.0 on 2021-12-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='link',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
