# Generated by Django 4.0 on 2021-12-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='genre',
            field=models.CharField(choices=[('adoption', 'Adoption'), ('info', 'Info'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=200, verbose_name="ז'אנר"),
        ),
        migrations.AlterField(
            model_name='articles',
            name='type',
            field=models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=10, verbose_name='סוג'),
        ),
    ]
