# Generated by Django 4.0 on 2021-12-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_alter_articles_genre_alter_articles_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='genre',
            field=models.CharField(choices=[('adoption', 'Adoption'), ('מידע', 'מידע'), ('training', 'Training'), ('other', 'Other')], default='other', max_length=200, verbose_name="ז'אנר"),
        ),
    ]
