# Generated by Django 4.0 on 2021-12-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_alter_articles_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='genre',
            field=models.CharField(choices=[('adoption', 'אימוץ'), ('info', 'מידע'), ('training', 'אילוף'), ('other', 'אחר')], default='other', max_length=200, verbose_name="ז'אנר"),
        ),
        migrations.AlterField(
            model_name='articles',
            name='type',
            field=models.CharField(choices=[('cat', 'חתול'), ('dog', 'כלב')], max_length=10, verbose_name='סוג'),
        ),
    ]
