# Generated by Django 3.2.9 on 2021-12-04 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('submitter', models.CharField(max_length=100, null=True)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], default='Dog', max_length=30)),
                ('breed', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('submission_date', models.DateTimeField(default=datetime.date.today)),
                ('image', models.ImageField(default=None, upload_to='animal/images')),
                ('vaccinations', models.ManyToManyField(blank=True, to='Animal.Vaccine')),
            ],
        ),
    ]
