# Generated by Django 3.2.9 on 2021-12-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='animal/images'),
        ),
    ]
