# Generated by Django 4.0 on 2021-12-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0002_remove_animal_adoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='Adoption',
            field=models.CharField(blank=True, choices=[('Y', 'yes'), ('N', 'No')], max_length=30),
        ),
    ]
