# Generated by Django 3.2.9 on 2021-12-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0002_alter_animal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='vaccinations',
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(default=None, upload_to='Animal/images'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
    ]
