# Generated by Django 3.2.9 on 2021-12-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0003_auto_20211205_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, upload_to='Animal/images'),
        ),
    ]
