# Generated by Django 4.0 on 2021-12-23 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0004_stats_alter_animal_adoption_alter_animal_breed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='MonthlyChange',
            new_name='current',
        ),
        migrations.AlterField(
            model_name='animal',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='תאריך קליטה'),
        ),
    ]
