# Generated by Django 4.0 on 2021-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0004_alter_animal_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Adoption',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=30),
        ),
    ]
