# Generated by Django 4.0 on 2021-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0005_alter_animal_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Adoption',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='No', max_length=30),
        ),
    ]
