# Generated by Django 4.0 on 2021-12-23 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0005_rename_monthlychange_stats_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='submission_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='תאריך קליטה'),
        ),
    ]
