# Generated by Django 4.0 on 2021-12-23 22:07

import Animal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0006_alter_animal_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='month',
            field=models.IntegerField(blank=True, default=0, validators=[Animal.models.validate_month]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='תאריך קליטה'),
        ),
    ]
