# Generated by Django 4.0 on 2021-12-23 22:09

import Animal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0007_stats_month_alter_animal_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='month',
            field=models.IntegerField(blank=True, default=1, validators=[Animal.models.validate_month]),
        ),
    ]
