# Generated by Django 4.0 on 2021-12-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0008_alter_stats_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Adoption',
            field=models.CharField(choices=[('N', 'לא'), ('Y', 'כן')], default='No', max_length=30, verbose_name='מוכן לאימוץ'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'זכר'), ('F', 'נקבה')], max_length=30, verbose_name='מין'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(choices=[('dog', 'כלב'), ('cat', 'חתול')], default='Dog', max_length=30, verbose_name='סוג'),
        ),
    ]
