# Generated by Django 4.0 on 2022-01-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0009_alter_animal_adoption_alter_animal_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=30, verbose_name='גזע'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('M', 'זכר'), ('F', 'נקבה')], default='M', max_length=30, verbose_name='מין'),
        ),
        migrations.AlterModelTable(
            name='stats',
            table='Stats',
        ),
    ]
