# Generated by Django 4.0 on 2022-01-02 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0010_alter_animal_breed_alter_animal_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stats',
            table='animal',
        ),
    ]
