# Generated by Django 4.0 on 2022-01-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0011_alter_stats_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'stats'},
        ),
        migrations.AlterModelTable(
            name='stats',
            table=None,
        ),
    ]
