# Generated by Django 4.0 on 2021-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskboard', '0005_alter_list_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_task',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
