# Generated by Django 4.0 on 2021-12-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskboard', '0006_list_task_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
