# Generated by Django 3.2.9 on 2021-12-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_rename_document_supplierregistration_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierregistration',
            old_name='quotation',
            new_name='bid_proposal',
        ),
    ]
