# Generated by Django 3.2.9 on 2021-11-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0002_article_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
