# Generated by Django 3.2.9 on 2021-11-29 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0002_reports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
