# Generated by Django 3.2.9 on 2021-11-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0003_alter_article_title'),
        ('adopter', '0003_delete_reports'),
    ]

    operations = [
    ]
