# Generated by Django 3.2.9 on 2021-11-29 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0005_auto_20211129_1353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stories',
        ),
    ]
