# Generated by Django 3.2.9 on 2021-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopter', '0006_delete_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('story', models.TextField(max_length=5000)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
