# Generated by Django 3.2.9 on 2021-12-04 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopter', '0007_stories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stories',
        ),
    ]
